<robot name="moving_car" xmlns:xacro="http://wiki.ros.org/xacro" >

    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0" />
    </material>

    <xacro:property name="base_link_radius" value="0.1" />
    <xacro:property name="base_link_length" value="0.08" />
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_length" value="0.0015" />
    <xacro:property name="PI" value="3.1415927" />
    <xacro:property name="lidi_space" value="0.015" />

    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="0.001" />
            </geometry>
        </visual>

        <gazebo reference="base_footprint">
            <material>Gazebo/Black</material>
        </gazebo>
    </link>

    <xacro:macro name="default_inertial" params="mass">
               <inertial>
                       <mass value="${mass}" />
                       <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                                iyy="1.0" iyz="0.0"
                                izz="1.0" />
               </inertial>
    </xacro:macro>


    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.08" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="yellow">
                <color rgba="0.8 0.3 0.1 0.5" />
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.1" length="0.08" />
            </geometry>
        </collision>
        <xacro:default_inertial mass="10"/>
        <gazebo reference="base_footprint">
          <material>Gazebo/Black</material>
      </gazebo>
    </link>

    <joint name="base_link2base_footprint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${lidi_space + base_link_length / 2 }" />
      </joint>

      <xacro:macro name="add_wheels" params="name flag">
        <link name="${name}_wheel">
          <visual>
            <geometry>
              <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
            <material name="black" />
          </visual>
          <gazebo reference="base_footprint">
            <material>Gazebo/Black</material>
        </gazebo>
        </link>
  
        <joint name="${name}_wheel2base_link" type="continuous">
          <parent link="base_link" />
          <child link="${name}_wheel" />
          <origin xyz="0 ${flag * base_link_radius} ${-(lidi_space + base_link_length / 2 - wheel_radius) }" />
          <axis xyz="0 1 0" />
        </joint>
      </xacro:macro>

      <xacro:add_wheels name="left" flag="1" />
      <xacro:add_wheels name="right" flag="-1" />



</robot>