set(_CATKIN_CURRENT_PACKAGE "simulate")
set(simulate_VERSION "0.0.0")
set(simulate_MAINTAINER "linhuangnan <linhuangnan@todo.todo>")
set(simulate_PACKAGE_FORMAT "2")
set(simulate_BUILD_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "urdf" "message_generation")
set(simulate_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "urdf" "message_generation")
set(simulate_BUILDTOOL_DEPENDS "catkin")
set(simulate_BUILDTOOL_EXPORT_DEPENDS )
set(simulate_EXEC_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "urdf" "message_generation")
set(simulate_RUN_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "urdf" "message_generation")
set(simulate_TEST_DEPENDS )
set(simulate_DOC_DEPENDS )
set(simulate_URL_WEBSITE "")
set(simulate_URL_BUGTRACKER "")
set(simulate_URL_REPOSITORY "")
set(simulate_DEPRECATED "")